# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: slowmail
 
test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: slowmail

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: slowmail